llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/rtc_base/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/rtc_base_approved/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/p2p/rtc_p2p/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/logging/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/rtc_event/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/stringutils/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/timeutils/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/platform_thread_types/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/criticalsection/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/crypto/options/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/pc/rtc_pc_base/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/checks/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/synchronization/sequence_checker/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/synchronization/yield_policy/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/rtc_error/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/system_wrappers/metrics/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/system_wrappers/field_trial/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/logging/ice_log/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/experiments/field_trial_parser/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/transport/stun_types/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/libjingle_peerconnection_api/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/weak_ptr/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/network/sent_packet/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/rtc_numerics/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/third_party/base64/base64/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/task_queue/task_queue/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/system/file_wrapper/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/rtc_base/platform_thread/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/rtc_event_log/rtc_event_log/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/rtp_parameters/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/transport/media/media_transport_interface/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/call/rtp_receiver/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/modules/rtp_rtcp/rtp_rtcp_format/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/media/rtc_media_base/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/units/data_size/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/units/time_delta/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/units/data_rate/*.o
llvm-ar -rcs trial/libwebrtc-lite.a webrtc-checkout/src/out/debug/obj/api/video/video_rtp_headers/*.o
